name: check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: install-ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          /bin/bash -c "$(curl -fsSL https://cli.moonbitlang.com/ubuntu_x86_64_moon_setup.sh)"
          echo "/home/runner/.moon/bin" >> $GITHUB_PATH
      # - name: install-macos
      #   if: ${{ matrix.os == 'macos-latest' }}
      #   run: |
      #         /bin/bash -c "$(curl -fsSL https://cli.moonbitlang.com/mac_intel_moon_setup.sh)"
      #         echo "/Users/runner/.moon/bin" >> $GITHUB_PATH
      # - name: install-windows
      #   if: ${{ matrix.os == 'windows-latest' }}
      #   run: |
      #         Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; irm https://cli.moonbitlang.cn/windows_moon_setup.ps1 | iex
      #         "C:\Users\runneradmin\.moon\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: moon version
        run: |
          moon version --all
          moonrun --version

      - name: moon check
        run: moon check --deny-warn

      - name: moon info
        run: |
          moon info
          git diff --exit-code

      - name: moon test
        run: |
          moon test
          moon test --target js

      - name: format diff
        run: |
          moon fmt
          git diff --exit-code
